name: "Summarize diffs of CloudFormation"
description: "GitHub Actions to summarize diffs of CloudFormation stack."
author: "taichi"
branding:
  icon: "upload-cloud"
  color: "orange"

inputs:
  aws-region:
    required: true
    description: "AWS Region, e.g. ap-northeast-1"
  cdk-outputs-directory:
    required: false
    description: "Name of the directory into which the cdk outputs."
    default: "cdk.out"
  stack-with-templates:
    required: false
    description: "Set one or more newline-delimited strings that pair the stack name with the template file path using =."
  force-drift-detection:
    required: false
    description: "Request forced detection of drift for the stack"
    default: "false"
  enable-drift-detection:
    required: false
    description: "Checks whether your CloudFormation stacks' actual configuration differs."
    default: "true"
  drift-delay-milliseconds:
    required: false
    default: 3000
  drift-maxAttempts:
    required: false
    default: 7
  drift-timeout-milliseconds:
    required: false
    default: 360000
  role-to-assume:
    required: false
    description: >-
      Use the provided credentials to assume an IAM role and configure the Actions
      environment with the assumed role credentials rather than with the provided
      credentials
  working-directory:
    required: false
    description: "Working directory of where to run the process."
  github-token:
    required: false
    description: "The GitHub token used to post comment."
    default: ${{ github.token }}

runs:
  using: "node20"
  main: "dist/index.js"
